### ISSUE TITLE
Audio only optie

### ISSUE THREAD

**Issue by Invictaz** [Reino17/xivid#14]
Batchgemist had een download optie (icm FFMPEG). Sinds kort is er ook zoiets voor Youtube-DL.
E.e.a. is wellicht interessant qua code.

https://github.com/grijul/yt-audio

Een audio only optie in Xivid met download zonder ingewikkelde FFMPEG commando's zou leuk zijn voor de verre toekomst

Dus 

Xivid.sh <url> -a 

ofzo

**Comment by Reino17** [comment]
Ik probeer te begrijpen waar je precies om vraagt. Kun je met een programma-url een concreet voorbeeld geven wat je dan van `xivid` verwacht dat het doet met zo'n optie?

**Comment by Invictaz** [comment]
Bijvoorbeeld 

Xivid.sh https://www.rtlxl.nl/nu-bij-videoland/4ab74ef4-540e-4cb8-8b00-0753ded76195 -a

Dan extract hij alleen de audio.

En ingewikkelde commando's typen op je mobiel werkt niet.

**Comment by Reino17** [comment]
`./xivid.sh -f hls-1 https://www.rtlxl.nl/nu-bij-videoland/4ab74ef4-540e-4cb8-8b00-0753ded76195`?

**Comment by Invictaz** [comment]
Dank. Hoe komt het dat het resultaat http is ipv https?

En waarom heeft RTL een audio only URL? Gebruiken ze die om te muxen met de video segments?

**Comment by Reino17** [comment]
Waarschijnlijk omdat het nog een oude (nog steeds werkende) API is? Geen idee. Zul je RTL moeten vragen.

Speciaal voor jou! ;) Ik denk gewoon voor mensen die een uitzending als een podcast willen beluisteren.  
Niet om te muxen in ieder geval. Check de programma-url maar eens met `-i`, dan zie je dat alle videostreams audio hebben (`m3u8[h264+aac]`).

**Comment by Invictaz** [comment]
Dank
