### ISSUE TITLE
Kijk links

### ISSUE THREAD

**Issue by vespino** [Reino17/xivid#15]
Enig idee waarom kijk links momenteel de melding “geen video beschikbaar” geven? Via downloadgemist kan ik de link wel downloaden.

Bijv https://kijk.nl/programmas/klein-maar-fijn/BvxAfhXDWBU/seizoen/166256168185/afleveringen/video/empty_episode-klein-maar-fijn-s1-e6-2021-01-11/NiHJ2IQwbua

**Comment by Reino17** [comment]
Kijk.nl heeft achter de schermen het een en ander wéér veranderd. Ik zal de extractor dus moeten updaten.  
Het was me eergisteren zelf ook al opgevallen. Ik ben er mee bezig.

Ik probeer het een dezer dagen door te voeren, maar omdat er veel meer commits in de pijplijn zitten waar ik druk mee bezig ben wordt het eerder volgend weekend, denk ik.

**Comment by vespino** [comment]
Ik krijg nu de volgende melding:

https://kijk.nl/programmas/marble-mania/Ufi3nq58r6M/seizoen/170529320404/afleveringen/video/empty_episode-marble-mania-s1-e1-2021-01-23/iKbACEk0Fl1

Error:
err:XPTY0004: Invalid conversion from ("Marble Mania", null) to type singleton
Possible backtrace:
  $000000000051704F: Q{http://www.w3.org/2005/xpath-functions}concat + 239
  $0000000000549A24: TXQTermJSONiqObjectConstructor + 580
  $0000000000540950: perhaps TXQTermBinaryOp + 5168 ? but unlikely
  $000000000052B66F: TXQTermDefineVariable + 447
  $00000000005256DD: perhaps Q{http://www.w3.org/2005/xpath-functions}concat + 59261 ? but unlikely

Call xidel with --trace-stack to get an actual backtrace

xivid: geen video(-informatie) beschikbaar.

**Comment by Reino17** [comment]
Stom! Ik had natuurlijk moeten checken of de uiteindelijke query met alle geteste urls zou werken. [Fixed](https://github.com/Reino17/xivid/commit/8ed1389eb64581653b7f17c77cc7e421406e4d3d).

**Comment by Reino17** [comment]
Hmm. Het werkt nog steeds niet, zie ik nu. Dit heeft het `xidel`'s `x:request()`-functie te maken. Hier moet ik even dieper in duiken.

**Comment by Invictaz** [comment]
![Screenshot_20210126-001621_Termux](https://user-images.githubusercontent.com/20338545/105778076-e1d67600-5f6b-11eb-9c9c-b0e80470536f.jpg)

**Comment by Reino17** [comment]
[Fixed](https://github.com/Reino17/xivid/commit/d53feafdc7b68517702c60834be58fda90855c82).

**Comment by vespino** [comment]
Top, nu werkt het weer. Nog een vraagje: ik heb de xivid.xqm in dezelfde map staan als xivid.sh, maar toch zeurt het script dat "Exception: Failed to load module /xivid.xqm". Als ik xivid.xqm in / plaats en het script met sudo aanroep lukt het vervolgens prima, ook als ik ${0%%/*} vervang door een . (punt). Nu moet ik dat echter bij iedere update vervangen.

**Comment by Reino17** [comment]
Bij nader inzien lijkt mij `${0%/*}` ook beter. Dan krijg je volgens mij altijd het volledige pad naar het script. Hetzelfde als wat `%~dp0` doet in Batch.  
Kun je dat eens proberen?

**Comment by vespino** [comment]
Dan werkt het prima (met ${0%/*} dus).

**Comment by ditmarvisser** [comment]
Ik krijg de melding "err:XPTY0004: Invalid conversion from ("Mr. Frank Visser doet uitspraak", "Bezem door de straat") to type singleton" weer. Hebben ze weer dingen veranderd achter de schermen?

**Comment by vespino** [comment]
@ditmarvisser heb je een linkje, dan kan ik eens testen voor je.

**Comment by ditmarvisser** [comment]
https://kijk.nl/programmas/mr-frank-visser-doet-uitspraak/ZMeF6bC3vW1/seizoen/188344360278/afleveringen/video/bezem-door-de-straat/7CFHn2lEXDW

**Comment by Reino17** [comment]
Ik zelf zie niet zo vaak dingen van Kijk, dus deze met zowel een serie-titel als een aflevering titel was ik nog niet tegengekomen.  
[Fixed](https://github.com/Reino17/xivid/commit/d5d9c4f9f4988bd437b5d6de667d5c03c1eda4a1).

**Comment by vespino** [comment]
Geüpdatet, getest, werkt.

**Comment by ditmarvisser** [comment]
Ik heb ook geupdate, getest, en deze melding is opgelost. Echter krijg ik alleen de subtitle streams te zien, en geen video of audio. Dit krijg ik als response:

X:\xivid\xivid>xivid.bat -i https://kijk.nl/programmas/mr-frank-visser-doet-uitspraak/ZMeF6bC3vW1/seizoen/188344360278/afleveringen/video/bezem-door-de-straat/7CFHn2lEXDW

Naam:       Kijk: Mr. Frank Visser doet uitspraak - Bezem door de straat S06E03
Datum:      2021-03-25T21:34:24Z
Tijdsduur:  PT41M57S
Gratis tot: 2026-03-25T21:34:24Z
Formaten:   id     formaat  taal
            sub-1  vtt      nl
            sub-2  vtt      nl (best)


Dit is bij meer Frank Visser afleveringen die ik heb getest.

**Comment by Reino17** [comment]
Bij mij werkt `xivid:info()` gewoon naar behoren:
```
xivid.bat -i https://kijk.nl/programmas/mr-frank-visser-doet-uitspraak/ZMeF6bC3vW1/seizoen/188344360278/afleveringen/video/bezem-door-de-straat/7CFHn2lEXDW
Naam:       Kijk: Mr. Frank Visser doet uitspraak - Bezem door de straat S06E03
Datum:      2021-03-25T21:34:24Z
Tijdsduur:  PT41M57S
Gratis tot: 2026-03-25T21:34:24Z
Formaten:   id     formaat         taal  resolutie        bitrate
            sub-1  vtt             nl
            sub-2  vtt             nl
            hls-0  m3u8[manifest]
            hls-1  m3u8[h264+aac]        448x252@25fps    507kbps
            hls-2  m3u8[h264+aac]        640x360@25fps    944kbps
            hls-3  m3u8[h264+aac]        768x432@25fps    1826kbps
            hls-4  m3u8[h264+aac]        1280x720@25fps   3476kbps
            hls-5  m3u8[h264+aac]        1920x1080@25fps  5126kbps
            hls-6  m3u8[h264+aac]        1920x1080@25fps  6776kbps (best)
```
Kun je het anders nog eens proberen? Het zou kunnen dat het HLS manifest even onbereikbaar was.

Werkt dat niet? Kun je dan vertellen welke `xidel` versie je gebruikt?

**Comment by ditmarvisser** [comment]
Interesant, bij mij blijft het met dezelfde command alleen de ondertitels geven. 

Ik gebruik xidel-0.9.9.20210309.7795.

Ik heb xidel-0.9.9.20200726.7433 geprobeerd, en daarmee krijg ik wel alle streams te zien. Er is dus iets in de nieuwere versies van xidel wat lastig doet. We hebben in ieder geval een oplossing door gewoon terug te gaan naar 9.9.7433.

**Comment by Reino17** [comment]
Dit is wel heel eigenaardig. Ik zelf maak gebruik van de laatste r7795 `xidel` build, ook in de codeblock in mijn vorige post. Niks aan de hand, zoals je ziet.

Maak je gebruik van de "gewone" of de OpenSSL variant?

Krijg je met de `-j` optie ook alleen de 2 ondertiteling-streams in de "formats"-array, of toch wel alle streams?
