### ISSUE TITLE
Mixcloud werkt niet meer

### ISSUE THREAD

**Issue by Invictaz** [Reino17/xivid#16]
![image](https://user-images.githubusercontent.com/20338545/106394045-c00d4100-63fa-11eb-80d7-54bbf0ef0bc9.png)

Url:

https://www.mixcloud.com/Bakermatmusic/bakermat-presents-the-circus-046
/?utm_campaign=notification_new_upload&utm_medium=email&utm_source=notification&
utm_content=html

Als ik de m3u8 opsla kan hij de segments wel binnenhalen, maar speelt hij ze niet meer af, of althans hij haalt een stuk of 350 segments binnen van 10 seconden, dat is nooit de hele file natuurlijk.

Oude stream url's

https://stream10.mixcloud.com/secure/c/m4a/64/0/0/1/c/6fcc-4335-4aaf-8305-84e709ccc1d9.m4a?sig=FJ29cabjN0VlZe_zdXQQcw

nieuwe stream urls's

https://audio8.mixcloud.com/secure/hls/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.
m4a/streamindex-a1.m3u8

Dus de HLS streams worden niet goed geopend. Misschien dat je weer m4a's moet hebben?
VLC moet normaal toch gewoon HLS kunnen openen?

1 van de fragmenten is

https://audio6.mixcloud.com/secure/dash2/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a/fragment-81-a1-x3.m4s

**Comment by Invictaz** [comment]
Previews staan hier

https://audiocdn8.mixcloud.com/previews/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.mp3

**Comment by Reino17** [comment]
Allemaal leuk en aardig, maar wat heb ik hier mee te maken?

- Ik ben geen VLC programmeur.
- Plaatjes ben ik nog steeds niet van gecharmeerd als het niet echt nodig is.
- Ik zie nergens een codeblock met de (error) uitvoer van `xivid` (incl. programma-url). Als het al een `xivid` probleem is.

Ik kan hier niks mee. Pas a.u.b. je post aan.

**Comment by Invictaz** [comment]
Als je zo gaat reageren, dan laat ik het erbij. Probeer eerst eens te waarderen wat iemand post, te testen wat hij post en kom dan terug. Ik ben niet je hondje. Dit heeft niks met VLC te maken, ik heb puur VLC gebruikt voor de output te testen die Xivid geeft. En ik heb er niks mee te maken dat jij plaatjes niet kan waarderen, dan had je dat in je readme moeten zetten.

**Comment by Invictaz** [comment]
Je vroeg naar output, 

```
https://www.mixcloud.com/Bakermatmusic/bakermat-presents-the-circus-046/?utm_campaign=notification_new_upload&utm_medium=email&utm_source=notification&utm_content=html

C:\Users\Invictaz\Downloads\Software\Batchgemist\xivid-master-31-1-2021\xivid-mast
er>xivid https://www.mixcloud.com/Bakermatmusic/bakermat-presents-the-circus-046
/?utm_campaign=notification_new_upload&utm_medium=email&utm_source=notification&
utm_content=html
xivid: url ongeldig.
utm_medium wordt niet herkend als een interne
of externe opdracht, programma of batchbestand.
utm_source wordt niet herkend als een interne
of externe opdracht, programma of batchbestand.
utm_content wordt niet herkend als een interne
of externe opdracht, programma of batchbestand.
```

Alleen als je het gedeelte achter 046/ weg knipt krijg je een output.

**Comment by Reino17** [comment]
Mocht een gebruiker een foutmelding krijgen met het script en dit met mij willen delen, dan zal ik het altijd waarderen als diegene dat duidelijk weet te vermelden, met alleen de informatie die ik nodig heb om die fout te reproduceren.

Ik hoop dat je begrijpt dat als cruciale informatie verwerkt zit in een screenshot, ik die dan eerst moet overtypen om er iets mee te kunnen doen, wat zeer onhandig is. Daarom code en foutmeldingen graag altijd in codeblocks.

Met `xivid.bat` zul je urls met een querystring altijd van aanhalingstekens moeten voorzien, om te voorkomen dat `cmd.exe` deze anders gaat interpreteren (met de `[...] wordt niet herkend als [...]` foutmeldingen als resultaat). Tekortkoming van `cmd`/Batch en niets aan te doen. Dus:
```
xivid.bat -j "https://www.mixcloud.com/Bakermatmusic/bakermat-presents-the-circus-046/?utm_campaign=notification_new_upload&utm_medium=email&utm_source=notification&utm_content=html"
{
  "name": "Bakermat - Bakermat presents The Circus #046",
  "date": "2021-01-29T11:52:13Z",
  "duration": "PT59M35S",
  "formats": [
    {
      "id": "pg-1",
      "format": "m4a[aac]",
      "url": "https://stream14.mixcloud.com/secure/c/m4a/64/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a?sig=TZRoJ3TctRW3K4E5WAEMxg"
    },
    {
      "id": "hls-0",
      "format": "m3u8[manifest]",
      "url": "https://audio12.mixcloud.com/secure/hls/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a/index.m3u8"
    },
    {
      "id": "hls-1",
      "format": "m3u8[aac]",
      "resolution": null,
      "bitrate": "68kbps",
      "url": "https://audio12.mixcloud.com/secure/hls/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a/streamindex-a1.m3u8"
    }
  ]
}
```

Deze audio-urls zijn beschikbaar en zijn voor zover ik kan zien (en horen) ook gewoon te decoderen:
```
ffmpeg.exe -hide_banner -i "https://stream14.mixcloud.com/secure/c/m4a/64/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a?sig=TZRoJ3TctRW3K4E5WAEMxg"
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'https://stream14.mixcloud.com/secure/c/m4a/64/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a?sig=TZRoJ3TctRW3K4E5WAEMxg':
  Metadata:
    major_brand     : M4A
    minor_version   : 1
    compatible_brands: M4A mp42isom
    creation_time   : 2021-01-29T11:52:14.000000Z
    iTunSMPB        :  00000000 00000920 000003E0 0000000004B4D700 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    encoder         : Nero AAC codec / 1.5.4.0
  Duration: 00:59:41.12, start: 0.052971, bitrate: 68 kb/s
    Chapter #0:0: start 0.105941, end 3581.173693
    Metadata:
      title           :
    Stream #0:0(und): Audio: aac (HE-AAC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 68 kb/s (default)
    Metadata:
      creation_time   : 2021-01-29T11:52:14.000000Z
      handler_name    : Sound Media Handler
      vendor_id       : [0][0][0][0]
At least one output file must be specified

ffmpeg.exe -hide_banner -i "https://audio12.mixcloud.com/secure/hls/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a/streamindex-a1.m3u8"
[hls @ 05108c40] Skip ('#EXT-X-ALLOW-CACHE:YES')
[hls @ 05108c40] Skip ('#EXT-X-VERSION:3')
[hls @ 05108c40] Opening 'https://audio12.mixcloud.com/secure/hls/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a/seg-1-a1.ts' for reading
[hls @ 05108c40] Opening 'https://audio12.mixcloud.com/secure/hls/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a/seg-2-a1.ts' for reading
Input #0, hls, from 'https://audio12.mixcloud.com/secure/hls/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a/streamindex-a1.m3u8':
  Duration: 00:59:41.12, start: 0.101000, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
At least one output file must be specified
```
Het probleem ligt dus wel degelijk bij VLC.  
Of... als jij daadwerkelijk de spatie die ik zie in de audio-url in jouw codeblock hebt gekoppiepeest, dan zal dat eerder de oorzaak zijn.

**Comment by Invictaz** [comment]
> Mocht een gebruiker een foutmelding krijgen met het script en dit met mij willen delen, dan zal ik het altijd waarderen als diegene dat duidelijk weet te vermelden, met alleen de informatie die ik nodig heb om die fout te reproduceren.
> 
> Ik hoop dat je begrijpt dat als cruciale informatie verwerkt zit in een screenshot, ik die dan eerst moet overtypen om er iets mee te kunnen doen, wat zeer onhandig is. Daarom code en foutmeldingen graag altijd in codeblocks.
> 
> Met `xivid.bat` zul je urls met een querystring altijd van aanhalingstekens moeten voorzien, om te voorkomen dat `cmd.exe` deze anders gaat interpreteren (met de `[...] wordt niet herkend als [...]` foutmeldingen als resultaat). Tekortkoming van `cmd`/Batch en niets aan te doen. Dus:
> 
> ```
> xivid.bat -j "https://www.mixcloud.com/Bakermatmusic/bakermat-presents-the-circus-046/?utm_campaign=notification_new_upload&utm_medium=email&utm_source=notification&utm_content=html"
> {
>   "name": "Bakermat - Bakermat presents The Circus #046",
>   "date": "2021-01-29T11:52:13Z",
>   "duration": "PT59M35S",
>   "formats": [
>     {
>       "id": "pg-1",
>       "format": "m4a[aac]",
>       "url": "https://stream14.mixcloud.com/secure/c/m4a/64/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a?sig=TZRoJ3TctRW3K4E5WAEMxg"
>     },
>     {
>       "id": "hls-0",
>       "format": "m3u8[manifest]",
>       "url": "https://audio12.mixcloud.com/secure/hls/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a/index.m3u8"
>     },
>     {
>       "id": "hls-1",
>       "format": "m3u8[aac]",
>       "resolution": null,
>       "bitrate": "68kbps",
>       "url": "https://audio12.mixcloud.com/secure/hls/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a/streamindex-a1.m3u8"
>     }
>   ]
> }
> ```
> 
> Deze audio-urls zijn beschikbaar en zijn voor zover ik kan zien (en horen) ook gewoon te decoderen:
> 
> ```
> ffmpeg.exe -hide_banner -i "https://stream14.mixcloud.com/secure/c/m4a/64/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a?sig=TZRoJ3TctRW3K4E5WAEMxg"
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'https://stream14.mixcloud.com/secure/c/m4a/64/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a?sig=TZRoJ3TctRW3K4E5WAEMxg':
>   Metadata:
>     major_brand     : M4A
>     minor_version   : 1
>     compatible_brands: M4A mp42isom
>     creation_time   : 2021-01-29T11:52:14.000000Z
>     iTunSMPB        :  00000000 00000920 000003E0 0000000004B4D700 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
>     encoder         : Nero AAC codec / 1.5.4.0
>   Duration: 00:59:41.12, start: 0.052971, bitrate: 68 kb/s
>     Chapter #0:0: start 0.105941, end 3581.173693
>     Metadata:
>       title           :
>     Stream #0:0(und): Audio: aac (HE-AAC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 68 kb/s (default)
>     Metadata:
>       creation_time   : 2021-01-29T11:52:14.000000Z
>       handler_name    : Sound Media Handler
>       vendor_id       : [0][0][0][0]
> At least one output file must be specified
> 
> ffmpeg.exe -hide_banner -i "https://audio12.mixcloud.com/secure/hls/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a/streamindex-a1.m3u8"
> [hls @ 05108c40] Skip ('#EXT-X-ALLOW-CACHE:YES')
> [hls @ 05108c40] Skip ('#EXT-X-VERSION:3')
> [hls @ 05108c40] Opening 'https://audio12.mixcloud.com/secure/hls/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a/seg-1-a1.ts' for reading
> [hls @ 05108c40] Opening 'https://audio12.mixcloud.com/secure/hls/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a/seg-2-a1.ts' for reading
> Input #0, hls, from 'https://audio12.mixcloud.com/secure/hls/5/4/1/1/5bbc-72a0-4a97-9f29-8b809ea64eca.m4a/streamindex-a1.m3u8':
>   Duration: 00:59:41.12, start: 0.101000, bitrate: 0 kb/s
>   Program 0
>     Metadata:
>       variant_bitrate : 0
>     Stream #0:0: Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
>     Metadata:
>       variant_bitrate : 0
>     Stream #0:1: Data: timed_id3 (ID3  / 0x20334449)
>     Metadata:
>       variant_bitrate : 0
> At least one output file must be specified
> ```
> 
> Het probleem ligt dus wel degelijk bij VLC.
> Of... als jij daadwerkelijk de spatie die ik zie in de audio-url in jouw codeblock hebt gekoppiepeest, dan zal dat eerder de oorzaak zijn.

Sommige screenshots zijn niet te copy pasten, en de error log van VLC blijft leeg (ook al heb ik die wel ingesteld in de config)

Dan is het gek dan xivid bij mij de HLS uitspuugt en niet die de m4a als voorkeursoptie. Eerst deed hij dat wel. 
Ik denk ook dat hij de regelafbreuk verkeerd geïnterpreteerd heeft. Het "markeren" in CMD is ook heel irritant, aangezien hij een hoop whitespacing meeneemt na de url. Er is voor zover ik weet geen andere manier om iets te selecteren en te kopiepeesten?

![image](https://user-images.githubusercontent.com/20338545/106404775-16e33c80-6434-11eb-90f4-bdfa74d3bb07.png)

Ik denk dat de regelafbreuk in notepad mij de das omdeed, als ik die handmatig corrigeer werkt het wel...

**Comment by Reino17** [comment]
> _Dan is het gek dan xivid bij mij de HLS uitspuugt en niet die de m4a als voorkeursoptie._

Zonder optie zal `xivid` in principe altijd het laatste formaat in de gecreëerde JSON weergeven. `hls-1` dus in dit geval.

> _Er is voor zover ik weet geen andere manier om iets te selecteren en te kopiepeesten?_

Niet dat ik weet. Tekst in `cmd` kopieer je altijd letterlijk zoals je het ziet, dus incl. regelafbreuk. Daar zul je altijd rekening mee moeten houden. Daarom gebruik ik ook altijd `[...] | clip` (Windows) als een programma of commando véél tekst teruggeeft.

> _je moet dat ook maar net allemaal weten hoe het formaat heet wat die m4a geeft._

Daar zijn `-i` en eventueel `-j` voor. Ik dacht dat je dat wel wist.

Ok, dan ga ik er van uit dat het allemaal kwam door de regelafbreuk in `cmd`. Dan kunnen we deze issue sluiten, of niet?

**Comment by Invictaz** [comment]
Kan dicht, wel laten staan voor referentie mogelijk later
