### ISSUE TITLE
kijk link

### ISSUE THREAD

**Issue by vespino** [Reino17/xivid#19]
Deze link levert geen download op... ligt dat aan kijk?

https://kijk.nl/programmas/het-blok-nieuw-zeeland/1JvxWYEGJor/seizoen/186085928084/afleveringen/video/empty_episode-het-blok-nieuw-zeeland-s5-e41-2021-04-20/lcfhXZik0Gl

Er lijkt alleen ondertiteling in te zitten.

**Comment by Reino17** [comment]
```
$ xidel -s --xquery '
  x:request({
    "headers":"Accept: application/json",
    "url":request-combine(
      "https://graph.kijk.nl/graphql",
      {
        "query":concat(
          "query{programs(guid:&quot;lcfhXZik0Gl&quot;){items{__typename,type,guid,title,duration,",
          "tvSeasonEpisodeNumber,seriesEpisodeNumber,seasonNumber,media{mediaContent{assetTypes,",
          "sourceUrl,type},availableDate,expirationDate,availabilityState},series{guid,title}}}}"
        )
      }
    )/url
  })/(json//mediaContent)()[type="m3u8"]
'
{
  "assetTypes": ["Packager Output: HLS FairPlay Manifest"],
  "sourceUrl": "https://vod-usp-nl.prd.talpatvcdn.nl/lcfhXZik0Gl/3ddfc335-45a3-7ea9-c007-bfa7cd165d1a/lcfhXZik0Gl_1618821639544.ism/master.m3u8",
  "type": "m3u8"
}
```

_"Packager Output: HLS **FairPlay** Manifest"_, dus DRM. Helaas.

In de Kijk extractor vind je helemaal onderaan:
```
(.//mediaContent)()[type="m3u8" and ends-with((assetTypes)(),"public")]/sourceUrl
```
Daarmee selecteer ik dus het HLS manifest, maar stel ik ook de voorwaarde dat de waarde van het attribuut `assetTypes` moet eindigen op _"public"_ (zoals bijv. bij de wel vrij toegankelijke _"Mr. Frank Visser doet uitspraak - Bezem door de straat S06E03"_ video in mijn notities). Op deze manier filter ik dus de DRM video's eruit.

**Comment by vespino** [comment]
Helder, dat zeggen ze er niet bij hè bij kijk.nl :)
