### ISSUE TITLE
RTLXL 1080P

### ISSUE THREAD

**Issue by Invictaz** [Reino17/xivid#20]
Het is op zijn minst vreemd te noemen dat RTLXL meestal in 720P is maar met sommige uitzonderingen.
Het is denk ik interessant om uit te vinden wat er wél en wat er niet in 1080P geupload wordt. Zijn dit alleen fragmenten? Zijn dit alleen nieuwsfragmenten, of is er van de diverse uitzendingen een "verborgen" 1080P methode opvraagbaar.

https://www.rtlxl.nl/programma/humberto/5c39a0d0-e8fc-4f33-b888-9a8a6b94bd4d

Ik weet dat er soms een DRM melding kan komen te staan op bovenstaande pagina, in de player, MAAR het is niet duidelijk of dat specifiek voor de 1080P formaten geldt. De encryptie is overal CBC

'Unable to instantiate a key system supporting the required combinations (DRM_NO_KEY_SYSTEM)'

![RTLXL](https://pbs.twimg.com/media/E90FdHgXsAMD2ps?format=jpg&name=large)

**Comment by Reino17** [comment]
> _Ik zie in elk geval wel iets met useragents dat ze daarmee goochelen._

Heb je iets specifieks?

**Comment by Invictaz** [comment]
Nog niet. Ik ben totaal geen held in die moderne geobfusceerde broncodes doorspitten. Waar is de tijd gebleven van gewoon HTML?
