### ISSUE TITLE
kijk.nl DRM?

### ISSUE THREAD

**Issue by vespino** [Reino17/xivid#21]
Is het over met kijk.nl links? Zitten die voortaan ook op de DRM?

**Comment by Reino17** [comment]
Hallo vespino,

Niet dat ik weet. Volgens mij is er niks veranderd. Sommige video's zijn beveiligd met DRM, andere niet.

**Comment by vespino** [comment]
@Reino17 sinds 4/5 april steeds meer, dus ik denk dat dit hetzelfde feest wordt als NPO.

**Comment by vespino** [comment]
@Invictaz alles van Massa is Kassa van voor 5-4, idem voor Vandaag Inside.

**Comment by Reino17** [comment]
Massa is Kassa van 29 maart en Vandaag Inside van 1 april lijken inderdaad de laatste uitzendingen zonder DRM te zijn. Triest.

Op dit moment filter ik alle DRM video's eruit. Ik heb er wel eens over na zitten denken...  ik _kan_ ze er natuurlijk gewoon inlaten (met eventueel een extra key-value-pair zoals `{"drm":true()}` in de JSON), maar heeft het nut? Je kunt de video's immers toch niet openen/bekijken.

**Comment by vespino** [comment]
@Reino17 heeft ook geen nut. Ik ga mijn download script ombouwen naar een script dat me een notificatie stuurt wanneer er een nieuwe aflevering beschikbaar komt ipv het dan te downloaden. Als ik dan verwijs naar de corresponderende app, krijg ik dat meteen op mijn scherm en kan ik deze meteen doorsturen naar de chromecast... althans dat is de theorie.

**Comment by Invictaz** [comment]
@Reino17 Jawel want Widevine L3 is beschikbaar

@vespino interesse in dat script.

**Comment by Reino17** [comment]
Ik ken geen (command-line-)tool die ondersteuning daarvoor heeft. Jij wel?

**Comment by Invictaz** [comment]
@Reino17 jawel maar logischerwijs wordt dat steeds relatief snel van Github verwijderd.

**Comment by vespino** [comment]
@Invictaz script? Mijn script bedoel je?

**Comment by ditmarvisser** [comment]
Dit betekent dat Kijk links voortaan niet meer te downloaden zijn? Daar is ook geen workaround voor te vinden? Jammer!

Ps. Dit geld al een tijdje voor npostart zo te zien?

**Comment by Reino17** [comment]
Ik heb net even gekeken naar de [laatste uitzending van Hart van Nederland](https://www.kijk.nl/programmas/hart-van-nederland-late-editie/5dSbua6GZif):
```
xidel.exe -se "x:request({'headers':'Accept: application/json','url':request-combine('https://graph.kijk.nl/graphql',{'query':'query{programs(guid:&quot;5dSbua6GZif&quot;){items{__typename,type,guid,title,duration,tvSeasonEpisodeNumber,seriesEpisodeNumber,seasonNumber,media{mediaContent{assetTypes,sourceUrl,type},availableDate,expirationDate,availabilityState},series{guid,title}}}}'})/url})/(json//items)()"
{
  "__typename": "Program",
  "type": "EPISODE",
  "guid": "5dSbua6GZif",
  "title": null,
  "duration": 1496.002,
  "tvSeasonEpisodeNumber": 102,
  "seriesEpisodeNumber": 9697,
  "seasonNumber": 2022,
  "media": [
    {
      "mediaContent": [
        {
          "assetTypes": ["Packager Output: HLS FairPlay Manifest"],
          "sourceUrl": "https://vod.prd1.talpatvcdn.nl/4169e1f194134a46b50716cbe360c31e/d6640161dc6742f9a8d3dd909deea8ea/8090c2be20294a89b811fc891eff4801/index.m3u8",
          "type": "m3u8"
        },
        {
          "assetTypes": ["Packager Output: Smooth PlayReady Manifest"],
          "sourceUrl": "https://vod.prd1.talpatvcdn.nl/4169e1f194134a46b50716cbe360c31e/680f243beaa341d98558ab1035ca111f/f54559bc544a4ede9bab1e61404a1e87/index.ism/Manifest",
          "type": "ism"
        },
        {
          "assetTypes": ["Packager Output: MPEG DASH Widevine Manifest"],
          "sourceUrl": "https://vod.prd1.talpatvcdn.nl/4169e1f194134a46b50716cbe360c31e/ba94badf69954f2b80c8016e0ccaad3d/f04bf2ba4ada4d28b0267d65f574f32e/index.mpd",
          "type": "dash"
        },
        {
          "assetTypes": ["Packager Output: DASH PlayReady Manifest"],
          "sourceUrl": "https://vod.prd1.talpatvcdn.nl/4169e1f194134a46b50716cbe360c31e/7116009110a0461a954ba1bec9b1f119/10c83c391917456d9e85c12dc4234641/index.mpd",
          "type": "dash"
        }
      ],
      "availableDate": "1649797324000",
      "expirationDate": "1681333324000",
      "availabilityState": true
    }
  ],
  "series": {
    "guid": "rJh5SGui6xI",
    "title": "Hart van Nederland - Late Editie"
  }
}
```

"FairPlay", "Widevine", "PlayReady"... het is allemaal DRM. Als zelfs een programma als Hart van Nederland wordt voorzien van DRM, dan zie ik het wel heel somber in voor de toekomst.

Als je deze video-urls probeert te openen met `ffmpeg`, dan krijg je een hoop errors te zien.  
Ik ben niet op de hoogte van een "workaround". Zal er misschien in een of andere vorm wel zijn, maar ik ga me daar niet mee bezig houden. Ik ben geen jurist, maar het omzeilen van DRM (een kopieerbeveiliging) is bij mijn weten strafbaar.

Voor NPOstart is het al weer 3 jaar geleden. Toch kom ik zo nu en dan bepaalde programma's tegen die om de een of andere reden NIET van DRM zijn voorzien en dus rechtstreeks zijn terug te bekijken.

**Comment by vespino** [comment]
Ik verzamel de linkjes naar de afleveringen wel en kijk ze via de native apps van de aanbieders. Wel door enkele reclameblokjes heen wurmen, maar goed, beter dan 19 min op een heel uur. Het feit dat de aflevering maar voor korte duur beschikbaar is (rtlxl althans) neem ik dan voor lief aangezien ik meestal toch dezelfde avond (of anders de dag erna) terugkijk. Heb ze wel nog even gemeld hun "url scheme" aan te passen (rtlxl/kijk).

Dank dat ik toch nog enkele maanden van dit script gebruik heb kunnen maken!
