### ISSUE TITLE
xivid: url wordt niet ondersteund.

### ISSUE THREAD

**Issue by vespino** [Reino17/xivid#23]
```
./xivid.sh -j https://www.npostart.nl/strandgasten/01-03-2023/AT_300008054

Error:
Internet/HTTP Error: 419
when talking to: https://www.npostart.nl/player/AT_300008054
xivid: url wordt niet ondersteund.
```

**Comment by Invictaz** [comment]
Die error 419 heb ik ook ooit eens gehad op andere scripts wel interessant

**Comment by Reino17** [comment]
Hallo vespino. Ik heb net het een en ander geüpdatet, waaronder de NPO extractor.

Grappig. Net zoals vier jaar geleden, toen ze het meerendeel van hun video's van DRM gingen voorzien, voeren ze nu ook updates uit rond eind februari, begin maart. Dit keer is het wat minder erg. Voor het genereren van het token zijn wat cookies nodig en gaat nu middels een POST-request. Dat zelfde geldt voor het HLS manifest.

Voor video's **zonder** DRM zou de extractor het weer moeten doen. De programma-url doe jij noemt heeft wel DRM, dus daar krijg je sowieso geen video-urls voor terug.

**Comment by vespino** [comment]
Getest en werkend bevonden. Tot volgend jaar maar weer dan! ;-)
