### ISSUE TITLE
Support nieuwe KIJK urls

### ISSUE THREAD

**Issue by Invictaz** [Reino17/xivid#24]
https://www.kijk.nl/programmas/recht-in-de-ogen-van/y3PRxdShXDF

Werkt niet met laatste Xivid versie. Url not supported.

**Comment by Reino17** [comment]
Je weet zeker dat je _'xivid.xqm'_ up-to-date is? Bij mij werkt ie gewoon (alhoewel er geen video-urls beschikbaar zijn, want DRM).  
Welke `xidel` versie gebruik je?

**Comment by Invictaz** [comment]
xidel-0.9.9.20230617.8842.e14a96920e01.androidarm

En de xivid.xqm is ook up to date ja

**Comment by Reino17** [comment]
Android. Dus ik ga er van uit dat je _'xivid.sh'_ gebruikt. Zou je _'xivid.sh'_ als volgt aan willen passen?
```diff
diff --git a/xivid.sh b/xivid.sh
index 1fe0e0c..ab13432 100755
--- a/xivid.sh
+++ b/xivid.sh
@@ -59,10 +59,10 @@ Voorbeelden:
   ./xivid.sh -f hls-$+sub-1 https://kijk.nl/video/AgvoU4AJTpy
 EOF
 }
-
+set -x
 if command -v xidel >/dev/null; then
   if [[ $(xidel --version | xidel -s - -e 'extract($raw,"\d{8}")') -ge 20210708 ]]; then
-    export XIDEL_OPTIONS="--silent --module=${0%/*}/xivid.xqm"
+    export XIDEL_OPTIONS="--verbose --trace --module=${0%/*}/xivid.xqm"
   else
     cat 1>&2 <<EOF
 xivid: '$(command -v xidel)' gevonden, maar versie is te oud.
@@ -192,7 +192,7 @@ eval "$(xidel -e '
     fmts:=$json/(formats)()/id
   )
   else ()
-' --output-format=bash 2>/dev/null)"
+' --output-format=bash)"

 if [[ ! $extractor ]]; then
   echo "xivid: url wordt niet ondersteund." 1>&2
```
Dan zien we wat meer van het proces.  
(De vele `x"" syntax is deprecated. Use `` from XPath 4` waarschuwingen kun je negeren. Zal ik nog wat op verzinnen.)

**Comment by Invictaz** [comment]
Hoe moet ik dit invoeren in Termux gewoon droppen?

**Comment by Reino17** [comment]
Dit is een "diffje". Een aantal kleine aanpassingen aan _'xivid.sh'_ inzichtelijk gemaakt.

Ik denk dat het handigste op dit moment is om _'xivid.sh'_ gewoon even in een text-editor te openen en die aanpassingen handmatig aan te passen. Heb je `vi` op Termux?

**Comment by Invictaz** [comment]
Als jij 1 gigabyte downloaden normaal vindt voor een tekst editor...
Je hebt wel nano en dan houdt 't op. 
![Screenshot_20230708_010323_Termux](https://github.com/Reino17/xivid/assets/20338545/5012356a-1127-49ba-88cf-1bdaf348b6e6)

**Comment by Reino17** [comment]
Nee, dat vind ik niet normaal. Ik weet niet hoe je daar bij komt. Wat ik ook niet normaal vind is dat je niet simpel een script kunt bewerken op Termux. En dan vind je het vreemd dat ik een pc heb. Tsja.

Nou, vooruit; [xivid.sh incl. die paar aanpassingen](https://rwijnsma.home.xs4all.nl/temp/xivid.sh).

Voor de rest ga ik je echt niet helpen met (basis dingen op) Termux.

**Comment by Invictaz** [comment]
Termux is de enige manier om het e.e.a. op een telefoon te draaien. 
En aangezien Android het allemaal steeds meer dichttimmerd moeten scripts gepatched worden. Van de positieve kant: Apple is ook over naar ARM dus veel programma's die op een telefoon draaien, draaien dan ook met een paar aanpassingen op een Mac.
