### ISSUE TITLE
Xivid updaten voor moderne Termux versies

### ISSUE THREAD

**Issue by Invictaz** [Reino17/xivid#25]
Xivid kijkt nog steeds naar Xidel in /usr/bin.
Dat kan niet meer op moderne Android versies, alleen met proot package in Termux, waarna een chroot commando gedraaid kan worden. Daarna kan xidel geinstalleerd worden middels install.sh. Allemaal omslachtig gedoe. 
Termux draait in de rest van de directories tegenwoordig niet ivm noexec permissieblokkades. Wat je kunt doen is alles in de $HOME directly gooien.

Dat vereist wel dat Xivid ook toestaat dat Xidel kan aangeroepen worden vanuit die directory. Ik heb ook geprobeerd te werken met termux-fix-shebang die oude vereiste op /usr/bin eruit zou snijden maar dat werkt niet.

Dus gelieve het script aan te passen dat Xidel in andere directories ook toegestaan is.

Zie https://wiki.termux.com/wiki/Differences_from_Linux

"Thus, all programs must be patched and recompiled to meet requirements of the Termux environment otherwise they will not be able to find their configuration files or other data."

De termux-exec alternatieve optie is niet handig.

**Comment by Reino17** [comment]
Niet specifiek alleen naar `/usr/bin`.  
https://github.com/Reino17/xivid/blob/master/README.md:
> _Plaats `xidel` in `/usr/bin`, **of ergens anders in `$PATH`**_

Zolang `xidel` in `$PATH` gevonden kan worden zou er niks aan de hand moeten zijn.

**Comment by Invictaz** [comment]
Je kunt $PATH niet aanpassen in Termux afaik

**Comment by Reino17** [comment]
Voer `echo "${PATH//:/$'\n'}"` maar eens in voor een overzicht van alle paths. Dan moet er toch een map zijn waar je `xidel` in kunt plaatsen, lijkt mij. Ik zou het wel heel raar vinden als je de PATH-variabele niet aan zou kunnen passen.

Een aantal jaren geleden heb ik Termux eens geprobeerd op mijn Android telefoon en wat ik me nog kan herinneren is dat ik het allemaal erg omslachtig en gebruiksonvriendelijk vond. Ik gebruik mijn telefoon eigenlijk nooit voor het uitvoeren van shell commando's, daar heb ik een pc voor, dus ik heb het nooit meer gebruikt.

**Comment by Invictaz** [comment]
Offtopic:

Wie gebruikt er nog een pc tegenwoordig, een telefoon is zo ontzettend krachtig geworden. En je kan vanaf elke locatie aan de gang. En een pc tablet verstookt zoveel meer energie en warmte voor puur een linkje op te halen. Sinds ik een goede smartphone heb gebruik ik mijn pc aanzienlijk minder.

**Comment by Invictaz** [comment]
Ontopic

![Screenshot_20230708_005907_Termux](https://github.com/Reino17/xivid/assets/20338545/1fcd891c-5331-4af9-ae33-1de96d276bbd)

**Comment by Reino17** [comment]
De afsluitende double-quote ben je vergeten.

**Comment by Reino17** [comment]
Ik heb hier toch nog even naar gekeken.

- https://stackoverflow.com/questions/10376206/what-is-the-preferred-bash-shebang
- https://android.stackexchange.com/questions/185682/path-for-bash-in-android-termux
- https://unix.stackexchange.com/questions/404163/force-shell-to-ignore-shebang
- https://wiki.termux.com/wiki/Termux-fix-shebang
- https://wiki.termux.com/wiki/Termux-exec

Ik denk dat je de shebang `#!/bin/bash` (regel 1 in _'xivid.sh'_) dus zou kunnen veranderen in `#!/data/data/com.termux/files/usr/bin/bash`, of misschien zelfs `#!$PREFIX/bin`, maar - voor zover ik het begrijp - het makkelijkste lijkt mij het installeren van `pkg install termux-exec`, waarna je shell-scripts zonder aanpassingen zou moeten kunnen uitvoeren.

**Comment by Invictaz** [comment]
Zou moeten kunnen. Maar het werkt dus niet. Ik heb dat fix shebang script verdraaid en het werkt niet.
