### ISSUE TITLE
Einde OpenSSL 1.1.1

### ISSUE THREAD

**Issue by Invictaz** [Reino17/xivid#26]
Einde voor oudere systemen?

https://tweakers.net/nieuws/213454/ondersteuning-van-openssl-111-is-afgelopen.html

**Comment by Reino17** [comment]
Nee hoor, want vanaf mei dit jaar heb ik al een aantal keren OpenSSL 3 [gecompileerd](https://rwijnsma.home.xs4all.nl/files/openssl/) (voor Windows in ieder geval), welke Xidel al sinds [16 augustus 2021 ondersteund](https://sourceforge.net/p/videlibri/code/ci/7a10975f886b6724ce681b8adb7071890c3afb73/).

Xidel ondersteunt OpenSSL 1.0.2 en 1.1.1 nog prima, maar aangezien het niet meer aan te raden is deze nog te gebruiken, zal ik de README wel even updaten.
