### ISSUE TITLE
Mogelijkheid tot inloggen NPO Plus

### ISSUE THREAD

**Issue by Tr71** [Reino17/xivid#5]
Hi,

Zou het misschien mogelijk zijn om bij de NPO te kunnen inloggen en op deze manier hogere kwaliteit streams te bekijken?

Groet

**Comment by Reino17** [comment]
Hallo Tr71,

Ik zelf heb geen ervaring met NPO Plus, maar als NPO Plus video's, net als gewone NPO video's, beveiligd zijn met DRM, dan heeft het niet zo veel zin om hier tijd in te stoppen.

Met `xidel` is het mogelijk om in te loggen op websites en data te ontrekken. Ik heb me hier alleen nog niet mee bezig gehouden.
