### ISSUE TITLE
download subtitles

### ISSUE THREAD

**Issue by vespino** [Reino17/xivid#6]
Is it possible to download subtitles together with the streams?

**Comment by Reino17** [comment]
Hallo vespino,

Strikt genomen download `xivid` natuurlijk niks. Het _ontleedt_ alleen.  
Ik heb er echter wel eens over nagedacht om meerdere formaten op te kunnen geven met `-f`. Dus bijv. `xivid -f hls-7+sub-2 <url>`, net zoals dat bij `youtube-dl` gaat.

Als je wat duidelijker aangeeft wat je bedoelt, misschien kan ik je dan beter helpen.

**Comment by vespino** [comment]
Mijn vrouw mist de ondertiteling bij Chateau Meiland, daar komt het eigenlijk op neer 🤣 Ik zou punten scoren als die kunnen worden “geinclude”.

**Comment by Reino17** [comment]
Zoiets als hier boven genoemd...
```
xivid -f <id>+<id> <url>
<video-url>
<subtitle-url>
```
...waarbij de output van het 2e formaat dus op een volgende regel komt, zou je daar mee uit de voeten kunnen?

**Comment by vespino** [comment]
Als ik het 1 voor 1 doe, dus eerst -f hls-7 en daarna -f sub-1 krijg ik van de bestanden de URLs. Het werkt niet met -f hls-7+sub-1

**Comment by Reino17** [comment]
Jij hebt een "issue" geopend met de vraag voor nieuwe functionaliteit. Dat bespreken we hier nu, dus logisch dat `-f hls-7+sub-1` nog niet werkt.

Ik weet niet of je een Unix of een Windows gebruiker bent en of je dus `xivid.sh`, of `xivid.bat` gebruikt. Ik ga er wel van uit dat je `ffmpeg` gebruikt om de hls-videostream (m3u8) te downloaden.

Als ik deze nieuwe functionaliteit zou toevoegen, dan zul je als gebruiker van deze 2 regels (de 2 urls) een `ffmpeg`-commando moeten maken. Mijn vraag was dus of je daarmee uit de voeten kunt.  
Ik zit eventueel nog op iets anders te broeden.

**Comment by vespino** [comment]
Oh dat was me dan niet helemaal duidelijk. Nou apart werkt het dus, dus voor nu ben ik geholpen!

**Comment by Reino17** [comment]
Dan heb ik _"together"_ in je eerste post verkeerd begrepen. Ik dacht dat je de video én de ondertiteling tegelijk wilde downloaden door ze met één commando te muxen (integreren).  
Ok, prima.
