### ISSUE TITLE
Downloaden video lukt niet

### ISSUE THREAD

**Issue by maikvandergaag** [Reino17/xivid#8]
Ik probeer een uitzending te downloaden van zin in zappelin waar mijn dochter op bezoek is geweest.
Vanuit xivid krijg ik echter de onderstaande melding:

xivid: geen video beschikbaar.

Zou je hier wellicht bij kunnen helpen?

**Comment by Reino17** [comment]
Hallo Maik,

Ik ga er van uit dat je een url als `https://www.npostart.nl/zin-in-zappelin/05-06-2020/AT_2134399` hebt ingevoerd.  
Deze video (zoals bijna alle video's van NPO) is beveiligd met DRM en kan dus niet gedownload worden. Helaas.

Je zou http://www.downloadgemist.nl/ kunnen proberen. Zij nemen de video op terwijl die wordt afgespeeld en weten op die manier de DRM beveiliging te omzeilen.

**Comment by maikvandergaag** [comment]
Hoi Reino,
Bedankt voor je snelle reactie ga het proberen!
